server:
  port: 9866
  servlet:
    context-path: /webdb
    session:
      timeout: 600m

logging:
  level:
    root: info

spring:
  application:
    name: webdb
  datasource:
    url: jdbc:h2:file:./webdb/config
    driverClassName: org.h2.Driver
    username: sa
    password:
  freemarker:
    number-format: '#'
    template-loader-path: classpath:/templates/
    suffix: .html
    charset: UTF-8
    cache: false
    content-type: text/html
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
